### ISSUE TITLE
输出文件 type为空

### ISSUE THREAD

**Issue by meijuji202** [GHkmmm/shrinkpng#1]
输出文件 type为空

**Comment by GHkmmm** [comment]
请问上传的图片类型是什么呢 可以提供一个简单的示例看看么

**Comment by GHkmmm** [comment]
> 输出文件 type为空

请问上传的图片类型是什么呢 可以提供一个简单的示例看看么

**Comment by meijuji202** [comment]
``

**Comment by meijuji202** [comment]
https://github.com/GHkmmm/shrinkpng/blob/e52bea3c4fff025defb7f2e0555e633420420ffb/src/shrink.ts#L85

**Comment by GHkmmm** [comment]
感谢 已修复在1.0.1
